idf_component_register(
    SRCS
        "main.c"
        "local_backend_provider.c"
    INCLUDE_DIRS "."
    REQUIRES
        app_core
        screen
        config_manager
        control_engine
        inverter_manager
        meter_manager
        network_manager
        safety_manager
        source_detection
        web_server
        cjson
        esp_app_format
        esp_lvgl_adapter
        esp_lcd_touch_gt911
        esp_lcd
        esp_timer
        esp_driver_gpio
)
