#include "pvdg_ui_pages.h"

#include <stdio.h>
#include <string.h>

#include "pvdg_ui_theme.h"

typedef struct { lv_obj_t *root,*badge,*power,*running_count,*breaker,*rated,*minimum,*safe_pv,*evidence; } generator_ui_t;
typedef struct { lv_obj_t *root,*badge,*power,*source_note,*solar,*generator,*grid,*balance; } load_ui_t;
typedef struct { lv_obj_t *root,*grid_import_energy,*grid_export_energy,*grid_live,*solar_live,*generator_live,*load_live,*stat_max,*stat_min,*stat_avg,*stat_demand,*note; } reports_ui_t;
static generator_ui_t s_generator;
static load_ui_t s_load;
static reports_ui_t s_reports;

static lv_obj_t *label(lv_obj_t *parent,const char *text,uint32_t color,const lv_font_t *font){ lv_obj_t *obj=lv_label_create(parent); lv_label_set_text(obj,text?text:""); pvdg_ui_style_label(obj,lv_color_hex(color),font); return obj; }
static lv_obj_t *page_root(lv_obj_t *parent){ lv_obj_t *root=lv_obj_create(parent); pvdg_ui_style_root(root); lv_obj_set_size(root,LV_PCT(100),LV_PCT(100)); lv_obj_set_layout(root,LV_LAYOUT_FLEX); lv_obj_set_flex_flow(root,LV_FLEX_FLOW_COLUMN); lv_obj_set_style_pad_all(root,PVDG_UI_GAP_MD,LV_PART_MAIN); lv_obj_set_style_pad_row(root,PVDG_UI_GAP_SM,LV_PART_MAIN); return root; }
static lv_obj_t *header(lv_obj_t *root,const char *title,const char *subtitle,uint32_t accent,lv_obj_t **badge_out){ lv_obj_t *row=lv_obj_create(root); pvdg_ui_style_root(row); lv_obj_set_width(row,LV_PCT(100)); lv_obj_set_height(row,46); lv_obj_set_layout(row,LV_LAYOUT_FLEX); lv_obj_set_flex_flow(row,LV_FLEX_FLOW_ROW); lv_obj_set_flex_align(row,LV_FLEX_ALIGN_START,LV_FLEX_ALIGN_CENTER,LV_FLEX_ALIGN_CENTER); lv_obj_t *texts=lv_obj_create(row); pvdg_ui_style_root(texts); lv_obj_set_flex_grow(texts,1); lv_obj_set_height(texts,LV_PCT(100)); lv_obj_set_layout(texts,LV_LAYOUT_FLEX); lv_obj_set_flex_flow(texts,LV_FLEX_FLOW_COLUMN); lv_obj_set_style_pad_row(texts,0,LV_PART_MAIN); label(texts,title,PVDG_UI_COLOR_TEXT,PVDG_UI_FONT_TITLE); label(texts,subtitle,PVDG_UI_COLOR_MUTED,PVDG_UI_FONT_BODY); lv_obj_t *badge=pvdg_ui_make_badge(row,"Unavailable",lv_color_hex(accent)); if(badge_out)*badge_out=badge; return row; }
static void set_measurement(lv_obj_t *target,const pvdg_ui_measurement_t *m,const char *unit,unsigned decimals){ char text[40]; pvdg_ui_format_measurement(text,sizeof(text),m,unit,decimals); pvdg_ui_label_set_if_changed(target,text); }
static void set_text(lv_obj_t *target,const char *text){ pvdg_ui_label_set_if_changed(target,text?text:""); }
static lv_obj_t *hero(lv_obj_t *parent,const char *title,uint32_t accent,lv_obj_t **value_out,lv_obj_t **note_out){ lv_obj_t *card=pvdg_ui_make_card(parent); lv_obj_set_width(card,LV_PCT(100)); lv_obj_set_height(card,86); lv_obj_set_layout(card,LV_LAYOUT_FLEX); lv_obj_set_flex_flow(card,LV_FLEX_FLOW_COLUMN); lv_obj_set_style_pad_row(card,1,LV_PART_MAIN); label(card,title,accent,PVDG_UI_FONT_BODY); lv_obj_t *value=label(card,"--",PVDG_UI_COLOR_TEXT,PVDG_UI_FONT_HERO); lv_obj_t *note=label(card,"Telemetry unavailable",PVDG_UI_COLOR_MUTED,PVDG_UI_FONT_BODY); if(value_out)*value_out=value; if(note_out)*note_out=note; return card; }
static lv_obj_t *metric_card(lv_obj_t *parent,const char *title,uint32_t accent,lv_obj_t **value_out){ lv_obj_t *card=pvdg_ui_make_card(parent); lv_obj_set_flex_grow(card,1); lv_obj_set_height(card,LV_PCT(100)); lv_obj_set_layout(card,LV_LAYOUT_FLEX); lv_obj_set_flex_flow(card,LV_FLEX_FLOW_COLUMN); lv_obj_set_style_pad_row(card,2,LV_PART_MAIN); label(card,title,accent,PVDG_UI_FONT_BODY); lv_obj_t *value=label(card,"--",PVDG_UI_COLOR_TEXT,PVDG_UI_FONT_TITLE); if(value_out)*value_out=value; return card; }

lv_obj_t *pvdg_ui_generator_create(lv_obj_t *parent){
    memset(&s_generator,0,sizeof(s_generator)); pvdg_ui_theme_init(); s_generator.root=page_root(parent);
    header(s_generator.root,"Generator","Run evidence, breaker state and loading",PVDG_UI_COLOR_GENERATOR,&s_generator.badge);
    lv_obj_t *note=NULL; hero(s_generator.root,"Measured Generator Power",PVDG_UI_COLOR_GENERATOR,&s_generator.power,&note); s_generator.evidence=note;
    lv_obj_t *row=lv_obj_create(s_generator.root); pvdg_ui_style_root(row); lv_obj_set_width(row,LV_PCT(100)); lv_obj_set_height(row,92); lv_obj_set_layout(row,LV_LAYOUT_FLEX); lv_obj_set_flex_flow(row,LV_FLEX_FLOW_ROW); lv_obj_set_style_pad_column(row,PVDG_UI_GAP_SM,LV_PART_MAIN);
    metric_card(row,"Running Units",PVDG_UI_COLOR_GENERATOR,&s_generator.running_count); metric_card(row,"Breaker",PVDG_UI_COLOR_GENERATOR,&s_generator.breaker); metric_card(row,"Running Rated",PVDG_UI_COLOR_GENERATOR,&s_generator.rated);
    lv_obj_t *row2=lv_obj_create(s_generator.root); pvdg_ui_style_root(row2); lv_obj_set_width(row2,LV_PCT(100)); lv_obj_set_flex_grow(row2,1); lv_obj_set_layout(row2,LV_LAYOUT_FLEX); lv_obj_set_flex_flow(row2,LV_FLEX_FLOW_ROW); lv_obj_set_style_pad_column(row2,PVDG_UI_GAP_SM,LV_PART_MAIN);
    metric_card(row2,"Required Minimum",PVDG_UI_COLOR_WARNING,&s_generator.minimum); metric_card(row2,"Safe PV Limit",PVDG_UI_COLOR_SOLAR,&s_generator.safe_pv);
    lv_obj_t *guard=pvdg_ui_make_card(row2); lv_obj_set_flex_grow(guard,1); label(guard,"Data Boundary",PVDG_UI_COLOR_TEXT,PVDG_UI_FONT_BODY); lv_obj_t *copy=label(guard,"No fuel, temperature, oil pressure or battery values are shown unless firmware exposes them.",PVDG_UI_COLOR_MUTED,PVDG_UI_FONT_BODY); lv_obj_set_width(copy,LV_PCT(100)); lv_label_set_long_mode(copy,LV_LABEL_LONG_WRAP); return s_generator.root;
}
void pvdg_ui_generator_apply_model(const pvdg_ui_model_t *model){
    if(!model||!s_generator.root){pvdg_ui_generator_show_unavailable();return;} set_measurement(s_generator.power,&model->generator.measured_kw,"kW",1);
    const uint32_t color=!model->generator.evidence_configured?PVDG_UI_COLOR_WARNING:model->generator.running?PVDG_UI_COLOR_GENERATOR:PVDG_UI_COLOR_SUCCESS;
    pvdg_ui_badge_set(s_generator.badge,!model->generator.evidence_configured?"Evidence not configured":model->generator.running?"Running":"Stopped",lv_color_hex(color));
    char text[40]; snprintf(text,sizeof(text),"%u",(unsigned)model->generator.running_count); set_text(s_generator.running_count,text); set_text(s_generator.breaker,!model->generator.breaker_known?"Unknown":model->generator.breaker_closed?"Closed":"Open"); set_measurement(s_generator.rated,&model->generator.running_rated_kw,"kW",1); set_measurement(s_generator.minimum,&model->generator.required_minimum_kw,"kW",1); set_measurement(s_generator.safe_pv,&model->generator.safe_pv_limit_kw,"kW",1); set_text(s_generator.evidence,model->generator.measured_kw.available?"Measured total from generator evidence/telemetry":"Generator measured power unavailable");
}
void pvdg_ui_generator_show_unavailable(void){ if(!s_generator.root)return; pvdg_ui_badge_set(s_generator.badge,"Unavailable",lv_color_hex(PVDG_UI_COLOR_INACTIVE)); set_text(s_generator.power,"--"); set_text(s_generator.running_count,"--"); set_text(s_generator.breaker,"Unknown"); set_text(s_generator.rated,"--"); set_text(s_generator.minimum,"--"); set_text(s_generator.safe_pv,"--"); set_text(s_generator.evidence,"Telemetry unavailable"); }

lv_obj_t *pvdg_ui_load_create(lv_obj_t *parent){
    memset(&s_load,0,sizeof(s_load)); pvdg_ui_theme_init(); s_load.root=page_root(parent); header(s_load.root,"Load","Measured when supported; otherwise explicitly derived",PVDG_UI_COLOR_LOAD,&s_load.badge); hero(s_load.root,"Facility Load",PVDG_UI_COLOR_LOAD,&s_load.power,&s_load.source_note);
    lv_obj_t *row=lv_obj_create(s_load.root); pvdg_ui_style_root(row); lv_obj_set_width(row,LV_PCT(100)); lv_obj_set_height(row,100); lv_obj_set_layout(row,LV_LAYOUT_FLEX); lv_obj_set_flex_flow(row,LV_FLEX_FLOW_ROW); lv_obj_set_style_pad_column(row,PVDG_UI_GAP_SM,LV_PART_MAIN); metric_card(row,"Solar Contribution",PVDG_UI_COLOR_SOLAR,&s_load.solar); metric_card(row,"Generator",PVDG_UI_COLOR_GENERATOR,&s_load.generator); metric_card(row,"Grid Signed",PVDG_UI_COLOR_GRID,&s_load.grid);
    lv_obj_t *balance=pvdg_ui_make_card(s_load.root); lv_obj_set_width(balance,LV_PCT(100)); lv_obj_set_flex_grow(balance,1); label(balance,"Balance Rule",PVDG_UI_COLOR_TEXT,PVDG_UI_FONT_BODY); s_load.balance=label(balance,"Derived load requires fresh Solar + Generator + signed Grid/PCC measurements.",PVDG_UI_COLOR_MUTED,PVDG_UI_FONT_BODY); lv_obj_set_width(s_load.balance,LV_PCT(100)); lv_label_set_long_mode(s_load.balance,LV_LABEL_LONG_WRAP); return s_load.root;
}
void pvdg_ui_load_apply_model(const pvdg_ui_model_t *model){
    if(!model||!s_load.root){pvdg_ui_load_show_unavailable();return;} set_measurement(s_load.power,&model->load.power_kw,"kW",1); set_measurement(s_load.solar,&model->solar.measured_kw,"kW",1); set_measurement(s_load.generator,&model->generator.measured_kw,"kW",1); set_measurement(s_load.grid,&model->grid.power_kw,"kW",1);
    if(!model->load.power_kw.available){ pvdg_ui_badge_set(s_load.badge,"Unavailable",lv_color_hex(PVDG_UI_COLOR_INACTIVE)); set_text(s_load.source_note,"Insufficient reliable measurements"); set_text(s_load.balance,"Load not shown: the adapter refuses to assume a missing source is zero."); }
    else if(model->load.derived){ pvdg_ui_badge_set(s_load.badge,"DERIVED",lv_color_hex(PVDG_UI_COLOR_WARNING)); set_text(s_load.source_note,"Solar + Generator + signed Grid/PCC"); set_text(s_load.balance,"Derived = Solar + Generator + Grid (+import / -export)."); }
    else { pvdg_ui_badge_set(s_load.badge,"MEASURED",lv_color_hex(PVDG_UI_COLOR_SUCCESS)); set_text(s_load.source_note,"Direct facility load measurement"); set_text(s_load.balance,"Direct facility load measurement is authoritative."); }
}
void pvdg_ui_load_show_unavailable(void){ if(!s_load.root)return; pvdg_ui_badge_set(s_load.badge,"Unavailable",lv_color_hex(PVDG_UI_COLOR_INACTIVE)); set_text(s_load.power,"--"); set_text(s_load.solar,"--"); set_text(s_load.generator,"--"); set_text(s_load.grid,"--"); set_text(s_load.source_note,"Telemetry unavailable"); set_text(s_load.balance,"No reliable load model."); }

lv_obj_t *pvdg_ui_reports_create(lv_obj_t *parent){
    memset(&s_reports,0,sizeof(s_reports)); pvdg_ui_theme_init(); s_reports.root=page_root(parent); header(s_reports.root,"Reports","Verified counters, live snapshot and EM500 statistical registers",PVDG_UI_COLOR_GRID,NULL);
    lv_obj_t *energy=lv_obj_create(s_reports.root); pvdg_ui_style_root(energy); lv_obj_set_width(energy,LV_PCT(100)); lv_obj_set_height(energy,92); lv_obj_set_layout(energy,LV_LAYOUT_FLEX); lv_obj_set_flex_flow(energy,LV_FLEX_FLOW_ROW); lv_obj_set_style_pad_column(energy,PVDG_UI_GAP_SM,LV_PART_MAIN); metric_card(energy,"Grid Import Energy",PVDG_UI_COLOR_GRID,&s_reports.grid_import_energy); metric_card(energy,"Grid Export Energy",PVDG_UI_COLOR_SUCCESS,&s_reports.grid_export_energy);
    lv_obj_t *live=lv_obj_create(s_reports.root); pvdg_ui_style_root(live); lv_obj_set_width(live,LV_PCT(100)); lv_obj_set_height(live,90); lv_obj_set_layout(live,LV_LAYOUT_FLEX); lv_obj_set_flex_flow(live,LV_FLEX_FLOW_ROW); lv_obj_set_style_pad_column(live,PVDG_UI_GAP_SM,LV_PART_MAIN); metric_card(live,"Grid",PVDG_UI_COLOR_GRID,&s_reports.grid_live); metric_card(live,"Solar",PVDG_UI_COLOR_SOLAR,&s_reports.solar_live); metric_card(live,"Generator",PVDG_UI_COLOR_GENERATOR,&s_reports.generator_live); metric_card(live,"Load",PVDG_UI_COLOR_LOAD,&s_reports.load_live);
    lv_obj_t *stats=lv_obj_create(s_reports.root); pvdg_ui_style_root(stats); lv_obj_set_width(stats,LV_PCT(100)); lv_obj_set_height(stats,90); lv_obj_set_layout(stats,LV_LAYOUT_FLEX); lv_obj_set_flex_flow(stats,LV_FLEX_FLOW_ROW); lv_obj_set_style_pad_column(stats,PVDG_UI_GAP_SM,LV_PART_MAIN); metric_card(stats,"Grid HI",PVDG_UI_COLOR_WARNING,&s_reports.stat_max); metric_card(stats,"Grid LO",PVDG_UI_COLOR_GRID,&s_reports.stat_min); metric_card(stats,"Grid AVG",PVDG_UI_COLOR_SUCCESS,&s_reports.stat_avg); metric_card(stats,"Max Demand",PVDG_UI_COLOR_LOAD,&s_reports.stat_demand);
    lv_obj_t *guard=pvdg_ui_make_card(s_reports.root); lv_obj_set_width(guard,LV_PCT(100)); lv_obj_set_flex_grow(guard,1); label(guard,"History Boundary",PVDG_UI_COLOR_TEXT,PVDG_UI_FONT_BODY); s_reports.note=label(guard,"EM500 HI/LO/AVG/MAX-DEMAND values are statistical register families, not timestamped samples. No time-series trend is fabricated.",PVDG_UI_COLOR_MUTED,PVDG_UI_FONT_BODY); lv_obj_set_width(s_reports.note,LV_PCT(100)); lv_label_set_long_mode(s_reports.note,LV_LABEL_LONG_WRAP); return s_reports.root;
}
void pvdg_ui_reports_apply_model(const pvdg_ui_model_t *model){ if(!model||!s_reports.root){pvdg_ui_reports_show_unavailable();return;} set_measurement(s_reports.grid_import_energy,&model->grid.imported_energy_kwh,"kWh",1); set_measurement(s_reports.grid_export_energy,&model->grid.exported_energy_kwh,"kWh",1); set_measurement(s_reports.grid_live,&model->grid.power_kw,"kW",1); set_measurement(s_reports.solar_live,&model->solar.measured_kw,"kW",1); set_measurement(s_reports.generator_live,&model->generator.measured_kw,"kW",1); set_measurement(s_reports.load_live,&model->load.power_kw,"kW",1); }
void pvdg_ui_reports_apply_em500_statistics(const pvdg_ui_em500_statistics_t *statistics){ if(!s_reports.root)return; if(!statistics){ set_text(s_reports.stat_max,"--"); set_text(s_reports.stat_min,"--"); set_text(s_reports.stat_avg,"--"); set_text(s_reports.stat_demand,"--"); return; } set_measurement(s_reports.stat_max,&statistics->blocks[PVDG_UI_EM500_STAT_MAXIMUM].active_power_kw,"kW",1); set_measurement(s_reports.stat_min,&statistics->blocks[PVDG_UI_EM500_STAT_MINIMUM].active_power_kw,"kW",1); set_measurement(s_reports.stat_avg,&statistics->blocks[PVDG_UI_EM500_STAT_AVERAGE].active_power_kw,"kW",1); set_measurement(s_reports.stat_demand,&statistics->blocks[PVDG_UI_EM500_STAT_DEMAND].active_power_kw,"kW",1); }
void pvdg_ui_reports_show_unavailable(void){ if(!s_reports.root)return; set_text(s_reports.grid_import_energy,"--"); set_text(s_reports.grid_export_energy,"--"); set_text(s_reports.grid_live,"--"); set_text(s_reports.solar_live,"--"); set_text(s_reports.generator_live,"--"); set_text(s_reports.load_live,"--"); set_text(s_reports.stat_max,"--"); set_text(s_reports.stat_min,"--"); set_text(s_reports.stat_avg,"--"); set_text(s_reports.stat_demand,"--"); }
