#include "pvdg_ui_diagnostics.h"
#include <math.h>
#include <stdio.h>
#include <string.h>
#include "pvdg_ui_theme.h"
typedef struct { lv_obj_t *root,*state_badge,*target,*uptime,*reset,*cpu,*tasks,*free_internal,*minimum_internal,*largest_internal,*fragmentation,*psram,*flash,*temperature,*temperature_note; } diagnostics_ui_t; static diagnostics_ui_t s;
pvdg_ui_resource_state_t pvdg_ui_resource_state_parse(const char *name){if(!name)return PVDG_UI_RESOURCE_UNKNOWN;if(strcmp(name,"healthy")==0)return PVDG_UI_RESOURCE_HEALTHY;if(strcmp(name,"review")==0)return PVDG_UI_RESOURCE_REVIEW;if(strcmp(name,"critical")==0)return PVDG_UI_RESOURCE_CRITICAL;return PVDG_UI_RESOURCE_UNKNOWN;}
const char *pvdg_ui_resource_state_label(pvdg_ui_resource_state_t state){switch(state){case PVDG_UI_RESOURCE_HEALTHY:return "Healthy";case PVDG_UI_RESOURCE_REVIEW:return "Review";case PVDG_UI_RESOURCE_CRITICAL:return "Critical";default:return "Unknown";}}
static lv_obj_t *section(lv_obj_t *p,const char *t){lv_obj_t *c=pvdg_ui_make_card(p);lv_obj_set_flex_grow(c,1);lv_obj_set_height(c,LV_PCT(100));lv_obj_set_layout(c,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(c,LV_FLEX_FLOW_COLUMN);lv_obj_set_style_pad_row(c,2,LV_PART_MAIN);pvdg_ui_make_title(c,t);return c;}
static void set_text(lv_obj_t *o,const char *t){if(o)pvdg_ui_label_set_if_changed(o,t?t:"--");} static void format_bytes(char *b,size_t n,uint64_t x){double m=(double)x/(1024.0*1024.0);if(m>=1.0)snprintf(b,n,"%.2f MiB",m);else snprintf(b,n,"%.1f KiB",(double)x/1024.0);} static void format_uptime(char *b,size_t n,uint64_t ms){uint64_t sec=ms/1000ULL,d=sec/86400ULL;sec%=86400ULL;uint64_t h=sec/3600ULL;sec%=3600ULL;uint64_t m=sec/60ULL;if(d>0)snprintf(b,n,"%llud %lluh %llum",(unsigned long long)d,(unsigned long long)h,(unsigned long long)m);else snprintf(b,n,"%lluh %llum",(unsigned long long)h,(unsigned long long)m);}
lv_obj_t *pvdg_ui_diagnostics_create(lv_obj_t *parent){memset(&s,0,sizeof(s));pvdg_ui_theme_init();s.root=lv_obj_create(parent);pvdg_ui_style_root(s.root);lv_obj_set_size(s.root,LV_PCT(100),LV_PCT(100));lv_obj_set_layout(s.root,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(s.root,LV_FLEX_FLOW_COLUMN);lv_obj_set_style_pad_all(s.root,PVDG_UI_GAP_MD,LV_PART_MAIN);lv_obj_set_style_pad_row(s.root,PVDG_UI_GAP_SM,LV_PART_MAIN);lv_obj_t *head=lv_obj_create(s.root);pvdg_ui_style_root(head);lv_obj_set_width(head,LV_PCT(100));lv_obj_set_height(head,44);lv_obj_set_layout(head,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(head,LV_FLEX_FLOW_ROW);lv_obj_set_flex_align(head,LV_FLEX_ALIGN_SPACE_BETWEEN,LV_FLEX_ALIGN_CENTER,LV_FLEX_ALIGN_CENTER);pvdg_ui_make_title(head,"Diagnostics / System Resources");s.state_badge=pvdg_ui_make_badge(head,"Unavailable",lv_color_hex(PVDG_UI_COLOR_INACTIVE));lv_obj_t *body=lv_obj_create(s.root);pvdg_ui_style_root(body);lv_obj_set_width(body,LV_PCT(100));lv_obj_set_flex_grow(body,1);lv_obj_set_layout(body,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(body,LV_FLEX_FLOW_ROW);lv_obj_set_style_pad_column(body,PVDG_UI_GAP_SM,LV_PART_MAIN);lv_obj_t *runtime=section(body,"Runtime");pvdg_ui_make_metric_row(runtime,"Target",&s.target);pvdg_ui_make_metric_row(runtime,"Uptime",&s.uptime);pvdg_ui_make_metric_row(runtime,"Reset reason",&s.reset);pvdg_ui_make_metric_row(runtime,"CPU",&s.cpu);pvdg_ui_make_metric_row(runtime,"Tasks",&s.tasks);lv_obj_t *memory=section(body,"Internal Heap");pvdg_ui_make_metric_row(memory,"Free",&s.free_internal);pvdg_ui_make_metric_row(memory,"Minimum free",&s.minimum_internal);pvdg_ui_make_metric_row(memory,"Largest block",&s.largest_internal);pvdg_ui_make_metric_row(memory,"Fragmentation",&s.fragmentation);lv_obj_t *storage=section(body,"External / Storage");pvdg_ui_make_metric_row(storage,"PSRAM free",&s.psram);pvdg_ui_make_metric_row(storage,"Flash",&s.flash);pvdg_ui_make_metric_row(storage,"Temperature",&s.temperature);s.temperature_note=pvdg_ui_make_muted(storage,"Temperature is shown only when firmware explicitly qualifies it as available.");lv_obj_set_width(s.temperature_note,LV_PCT(100));lv_label_set_long_mode(s.temperature_note,LV_LABEL_LONG_WRAP);pvdg_ui_diagnostics_show_unavailable();return s.root;}
void pvdg_ui_diagnostics_apply(const pvdg_ui_system_resources_t *r){if(!s.root)return;if(!r||!r->available){pvdg_ui_diagnostics_show_unavailable();return;}uint32_t c=PVDG_UI_COLOR_INACTIVE;if(r->resource_state==PVDG_UI_RESOURCE_HEALTHY)c=PVDG_UI_COLOR_SUCCESS;else if(r->resource_state==PVDG_UI_RESOURCE_REVIEW)c=PVDG_UI_COLOR_WARNING;else if(r->resource_state==PVDG_UI_RESOURCE_CRITICAL)c=PVDG_UI_COLOR_DANGER;pvdg_ui_badge_set(s.state_badge,pvdg_ui_resource_state_label(r->resource_state),lv_color_hex(c));set_text(s.target,r->target&&r->target[0]?r->target:"--");char t[64];format_uptime(t,sizeof(t),r->uptime_ms);set_text(s.uptime,t);set_text(s.reset,r->reset_reason_name&&r->reset_reason_name[0]?r->reset_reason_name:"unknown");if(r->cpu_frequency_available)snprintf(t,sizeof(t),"%u cores · %u MHz",(unsigned)r->cpu_cores,(unsigned)r->cpu_frequency_mhz);else snprintf(t,sizeof(t),"%u cores · -- MHz",(unsigned)r->cpu_cores);set_text(s.cpu,t);snprintf(t,sizeof(t),"%u",(unsigned)r->task_count);set_text(s.tasks,t);format_bytes(t,sizeof(t),r->free_internal_heap_bytes);set_text(s.free_internal,t);format_bytes(t,sizeof(t),r->minimum_internal_heap_bytes);set_text(s.minimum_internal,t);format_bytes(t,sizeof(t),r->largest_internal_block_bytes);set_text(s.largest_internal,t);if(isfinite(r->internal_fragmentation_ratio)){snprintf(t,sizeof(t),"%.0f%%",r->internal_fragmentation_ratio*100.0);set_text(s.fragmentation,t);}else set_text(s.fragmentation,"--");if(r->psram_available){format_bytes(t,sizeof(t),r->psram_free_bytes);set_text(s.psram,t);}else set_text(s.psram,"Not available");if(r->flash_size_available){format_bytes(t,sizeof(t),r->flash_size_bytes);set_text(s.flash,t);}else set_text(s.flash,"--");if(r->temperature_available&&isfinite(r->temperature_c)){snprintf(t,sizeof(t),"%.1f °C",r->temperature_c);set_text(s.temperature,t);}else set_text(s.temperature,"--");set_text(s.temperature_note,r->temperature_note&&r->temperature_note[0]?r->temperature_note:r->temperature_available?"Firmware-qualified temperature reading":"Temperature unavailable from firmware");}
void pvdg_ui_diagnostics_show_unavailable(void){if(!s.root)return;pvdg_ui_badge_set(s.state_badge,"Unavailable",lv_color_hex(PVDG_UI_COLOR_INACTIVE));lv_obj_t *labels[]={s.target,s.uptime,s.reset,s.cpu,s.tasks,s.free_internal,s.minimum_internal,s.largest_internal,s.fragmentation,s.psram,s.flash,s.temperature};for(size_t i=0;i<sizeof(labels)/sizeof(labels[0]);++i)set_text(labels[i],"--");set_text(s.temperature_note,"System-resource telemetry unavailable.");}
