#include "pvdg_ui_wifi.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "pvdg_ui_theme.h"
typedef struct { lv_obj_t *root,*badge,*ssid,*ip,*rssi,*scan,*reconnect,*selected,*password,*save,*msg,*rows[PVDG_UI_WIFI_MAX_NETWORKS],*row_name[PVDG_UI_WIFI_MAX_NETWORKS],*row_meta[PVDG_UI_WIFI_MAX_NETWORKS]; pvdg_ui_wifi_callbacks_t cb; pvdg_ui_wifi_config_t config; char selected_ssid[PVDG_UI_TEXT_MEDIUM]; bool secure[PVDG_UI_WIFI_MAX_NETWORKS],supported[PVDG_UI_WIFI_MAX_NETWORKS],selected_secure,config_available,busy; } wifi_ui_t; static wifi_ui_t s;
static lv_obj_t *label(lv_obj_t *p,const char *t,uint32_t c){lv_obj_t *o=lv_label_create(p);lv_label_set_text(o,t?t:"");pvdg_ui_style_label(o,lv_color_hex(c),PVDG_UI_FONT_BODY);return o;}static lv_obj_t *button(lv_obj_t *p,const char *t,lv_event_cb_t cb){lv_obj_t *b=lv_button_create(p);lv_obj_set_height(b,PVDG_UI_TOUCH_MIN);lv_obj_t *l=label(b,t,PVDG_UI_COLOR_TEXT);lv_obj_center(l);lv_obj_add_event_cb(b,cb,LV_EVENT_CLICKED,NULL);return b;}static void scan_event(lv_event_t *e){(void)e;if(!s.busy&&s.cb.request_scan)s.cb.request_scan(s.cb.user);}static void reconnect_event(lv_event_t *e){(void)e;if(!s.busy&&s.cb.request_reconnect)s.cb.request_reconnect(s.cb.user);}static void row_event(lv_event_t *e){intptr_t i=(intptr_t)lv_event_get_user_data(e);if(i<0||i>=PVDG_UI_WIFI_MAX_NETWORKS||!s.supported[i])return;const char *name=lv_label_get_text(s.row_name[i]);snprintf(s.selected_ssid,sizeof(s.selected_ssid),"%s",name?name:"");s.selected_secure=s.secure[i];pvdg_ui_label_set_if_changed(s.selected,s.selected_ssid);lv_textarea_set_text(s.password,"");}
static void save_event(lv_event_t *e){(void)e;if(s.busy||!s.cb.submit_config||!s.config_available||!s.selected_ssid[0])return;pvdg_ui_wifi_config_t next;bool changed=false;char error[160]={0};const char *pw=lv_textarea_get_text(s.password);pvdg_ui_wifi_config_result_t r=pvdg_ui_wifi_prepare_primary(&s.config,s.selected_ssid,pw?pw:"",s.selected_secure,&next,&changed,error,sizeof(error));if(r!=PVDG_UI_WIFI_CONFIG_OK){pvdg_ui_label_set_if_changed(s.msg,error[0]?error:"Wi-Fi validation failed.");return;}s.cb.submit_config(&next,changed,s.cb.user);lv_textarea_set_text(s.password,"");pvdg_ui_label_set_if_changed(s.msg,"Wi-Fi configuration submitted; restart may be required.");}
lv_obj_t *pvdg_ui_wifi_create(lv_obj_t *parent,const pvdg_ui_wifi_callbacks_t *cb){memset(&s,0,sizeof(s));if(cb)s.cb=*cb;s.root=lv_obj_create(parent);pvdg_ui_style_root(s.root);lv_obj_set_size(s.root,LV_PCT(100),LV_PCT(100));lv_obj_set_layout(s.root,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(s.root,LV_FLEX_FLOW_COLUMN);lv_obj_set_style_pad_all(s.root,PVDG_UI_GAP_MD,LV_PART_MAIN);pvdg_ui_make_title(s.root,"Wi-Fi Manager");s.badge=pvdg_ui_make_badge(s.root,"Offline",lv_color_hex(PVDG_UI_COLOR_DANGER));pvdg_ui_make_metric_row(s.root,"SSID",&s.ssid);pvdg_ui_make_metric_row(s.root,"IP",&s.ip);pvdg_ui_make_metric_row(s.root,"Signal",&s.rssi);lv_obj_t *a=lv_obj_create(s.root);pvdg_ui_style_root(a);lv_obj_set_width(a,LV_PCT(100));lv_obj_set_height(a,52);lv_obj_set_layout(a,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(a,LV_FLEX_FLOW_ROW);s.scan=button(a,"Scan",scan_event);s.reconnect=button(a,"Reconnect",reconnect_event);s.selected=label(s.root,"Select a network",PVDG_UI_COLOR_TEXT);s.password=lv_textarea_create(s.root);lv_textarea_set_one_line(s.password,true);lv_textarea_set_password_mode(s.password,true);lv_textarea_set_placeholder_text(s.password,"Password (never prefilled)");lv_obj_set_width(s.password,LV_PCT(100));s.save=button(s.root,"Save Primary Wi-Fi",save_event);lv_obj_set_width(s.save,LV_PCT(100));s.msg=pvdg_ui_make_muted(s.root,"Load current Wi-Fi baseline before saving.");for(uint8_t i=0;i<PVDG_UI_WIFI_MAX_NETWORKS;i++){s.rows[i]=lv_button_create(s.root);lv_obj_set_width(s.rows[i],LV_PCT(100));lv_obj_set_height(s.rows[i],34);lv_obj_set_layout(s.rows[i],LV_LAYOUT_FLEX);lv_obj_set_flex_flow(s.rows[i],LV_FLEX_FLOW_ROW);s.row_name[i]=label(s.rows[i],"--",PVDG_UI_COLOR_TEXT);lv_obj_set_flex_grow(s.row_name[i],1);s.row_meta[i]=label(s.rows[i],"",PVDG_UI_COLOR_MUTED);lv_obj_add_event_cb(s.rows[i],row_event,LV_EVENT_CLICKED,(void*)(intptr_t)i);lv_obj_add_flag(s.rows[i],LV_OBJ_FLAG_HIDDEN);}return s.root;}
void pvdg_ui_wifi_apply(const pvdg_ui_model_t *m,const pvdg_ui_wifi_scan_t *scan){if(!s.root)return;if(m){pvdg_ui_badge_set(s.badge,m->network.online?"Online":"Offline",lv_color_hex(m->network.online?PVDG_UI_COLOR_SUCCESS:PVDG_UI_COLOR_DANGER));pvdg_ui_label_set_if_changed(s.ssid,m->network.ssid[0]?m->network.ssid:"--");pvdg_ui_label_set_if_changed(s.ip,m->network.ip[0]?m->network.ip:"--");char r[24];snprintf(r,sizeof(r),"%d dBm",m->network.rssi);pvdg_ui_label_set_if_changed(s.rssi,r);}for(uint8_t i=0;i<PVDG_UI_WIFI_MAX_NETWORKS;i++){lv_obj_add_flag(s.rows[i],LV_OBJ_FLAG_HIDDEN);s.secure[i]=false;s.supported[i]=false;}if(!scan)return;uint8_t count=scan->count>PVDG_UI_WIFI_MAX_NETWORKS?PVDG_UI_WIFI_MAX_NETWORKS:scan->count;for(uint8_t i=0;i<count;i++){const pvdg_ui_wifi_network_t *n=&scan->networks[i];pvdg_ui_label_set_if_changed(s.row_name[i],n->ssid[0]?n->ssid:"<hidden>");char meta[96];snprintf(meta,sizeof(meta),"%d dBm  Ch %u  %s",n->rssi,(unsigned)n->channel,n->security[0]?n->security:"Unknown");pvdg_ui_label_set_if_changed(s.row_meta[i],meta);s.secure[i]=n->secure;s.supported[i]=n->supported;if(n->supported)lv_obj_remove_state(s.rows[i],LV_STATE_DISABLED);else lv_obj_add_state(s.rows[i],LV_STATE_DISABLED);lv_obj_remove_flag(s.rows[i],LV_OBJ_FLAG_HIDDEN);}if(scan->scan_running)lv_obj_add_state(s.scan,LV_STATE_DISABLED);else if(!s.busy)lv_obj_remove_state(s.scan,LV_STATE_DISABLED);}
void pvdg_ui_wifi_set_config_snapshot(const pvdg_ui_wifi_config_t *c,bool available){if(!s.root)return;char e[128]={0};s.config_available=available&&c&&pvdg_ui_wifi_config_valid(c,e,sizeof(e));if(s.config_available){s.config=*c;pvdg_ui_label_set_if_changed(s.msg,"Wi-Fi baseline loaded.");}else{memset(&s.config,0,sizeof(s.config));pvdg_ui_label_set_if_changed(s.msg,e[0]?e:"Wi-Fi baseline unavailable.");}}
void pvdg_ui_wifi_set_action_state(bool busy,const char *message){s.busy=busy;if(!s.root)return;lv_obj_t *items[]={s.scan,s.reconnect,s.save};for(size_t i=0;i<3;i++){if(busy)lv_obj_add_state(items[i],LV_STATE_DISABLED);else lv_obj_remove_state(items[i],LV_STATE_DISABLED);}if(message)pvdg_ui_label_set_if_changed(s.msg,message);}
