#include "pvdg_ui_engineering.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "pvdg_ui_theme.h"
typedef struct{lv_obj_t*root,*badge,*status,*password,*login,*login_label,*sections[8];pvdg_ui_engineering_callbacks_t cb;bool authenticated,write_ok,busy;}eng_t;static eng_t s;static const char*n[]={"Source Setup","Meter Setup","Inverter Setup","Export Control","Safety Limits","Network","Diagnostics","Configuration"};
static lv_obj_t*label(lv_obj_t*p,const char*t){lv_obj_t*o=lv_label_create(p);lv_label_set_text(o,t?t:"");pvdg_ui_style_label(o,lv_color_hex(PVDG_UI_COLOR_TEXT),PVDG_UI_FONT_BODY);return o;}static void auth(lv_event_t*e){(void)e;if(s.busy)return;if(s.authenticated){if(s.cb.request_logout)s.cb.request_logout(s.cb.user);return;}const char*p=lv_textarea_get_text(s.password);if(p&&p[0]&&s.cb.submit_password)s.cb.submit_password(p,s.cb.user);lv_textarea_set_text(s.password,"");}static void open(lv_event_t*e){if(s.cb.open_section)s.cb.open_section((pvdg_ui_engineering_section_t)(intptr_t)lv_event_get_user_data(e),s.cb.user);}
lv_obj_t*pvdg_ui_engineering_create(lv_obj_t*parent,const pvdg_ui_engineering_callbacks_t*cb){memset(&s,0,sizeof(s));if(cb)s.cb=*cb;s.root=lv_obj_create(parent);pvdg_ui_style_root(s.root);lv_obj_set_size(s.root,LV_PCT(100),LV_PCT(100));lv_obj_set_layout(s.root,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(s.root,LV_FLEX_FLOW_COLUMN);lv_obj_set_style_pad_all(s.root,PVDG_UI_GAP_MD,LV_PART_MAIN);lv_obj_t*h=lv_obj_create(s.root);pvdg_ui_style_root(h);lv_obj_set_width(h,LV_PCT(100));lv_obj_set_height(h,48);lv_obj_set_layout(h,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(h,LV_FLEX_FLOW_ROW);pvdg_ui_make_title(h,"Engineering / Commissioning");s.badge=pvdg_ui_make_badge(h,"Locked",lv_color_hex(PVDG_UI_COLOR_WARNING));s.status=pvdg_ui_make_muted(s.root,"Engineering session: locked");lv_obj_t*a=lv_obj_create(s.root);pvdg_ui_style_root(a);lv_obj_set_width(a,LV_PCT(100));lv_obj_set_height(a,52);lv_obj_set_layout(a,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(a,LV_FLEX_FLOW_ROW);s.password=lv_textarea_create(a);lv_textarea_set_one_line(s.password,true);lv_textarea_set_password_mode(s.password,true);lv_textarea_set_placeholder_text(s.password,"Engineering password / setup code");lv_obj_set_flex_grow(s.password,1);s.login=lv_button_create(a);lv_obj_set_width(s.login,160);s.login_label=label(s.login,"Authenticate");lv_obj_center(s.login_label);lv_obj_add_event_cb(s.login,auth,LV_EVENT_CLICKED,NULL);lv_obj_t*g=lv_obj_create(s.root);pvdg_ui_style_root(g);lv_obj_set_width(g,LV_PCT(100));lv_obj_set_flex_grow(g,1);lv_obj_set_layout(g,LV_LAYOUT_GRID);static lv_coord_t cols[]={LV_GRID_FR(1),LV_GRID_FR(1),LV_GRID_FR(1),LV_GRID_FR(1),LV_GRID_TEMPLATE_LAST};static lv_coord_t rows[]={LV_GRID_FR(1),LV_GRID_FR(1),LV_GRID_TEMPLATE_LAST};lv_obj_set_grid_dsc_array(g,cols,rows);for(uint8_t i=0;i<8;i++){s.sections[i]=lv_button_create(g);lv_obj_set_grid_cell(s.sections[i],LV_GRID_ALIGN_STRETCH,i%4,1,LV_GRID_ALIGN_STRETCH,i/4,1);lv_obj_t*l=label(s.sections[i],n[i]);lv_obj_center(l);lv_obj_add_event_cb(s.sections[i],open,LV_EVENT_CLICKED,(void*)(intptr_t)i);lv_obj_add_state(s.sections[i],LV_STATE_DISABLED);}if(s.cb.request_session_refresh)s.cb.request_session_refresh(s.cb.user);return s.root;}
void pvdg_ui_engineering_apply(const pvdg_ui_model_t*m,const pvdg_ui_engineering_state_t*st){(void)m;if(!s.root)return;s.authenticated=st&&st->authenticated;s.write_ok=st&&st->write_contract_verified&&!st->setup_required;bool locked=st&&st->locked_out;pvdg_ui_badge_set(s.badge,locked?"Locked out":s.authenticated?"Authenticated":"Locked",lv_color_hex(locked?PVDG_UI_COLOR_DANGER:s.authenticated?PVDG_UI_COLOR_SUCCESS:PVDG_UI_COLOR_WARNING));char t[160];if(st&&st->message&&st->message[0])snprintf(t,sizeof(t),"%s",st->message);else if(s.authenticated)snprintf(t,sizeof(t),"Engineering session active%s",s.write_ok?" · writes enabled":" · read-only");else snprintf(t,sizeof(t),"Engineering session: locked");pvdg_ui_label_set_if_changed(s.status,t);pvdg_ui_label_set_if_changed(s.login_label,s.authenticated?"Logout":"Authenticate");if(s.authenticated)lv_obj_add_flag(s.password,LV_OBJ_FLAG_HIDDEN);else lv_obj_remove_flag(s.password,LV_OBJ_FLAG_HIDDEN);for(uint8_t i=0;i<8;i++){bool diag=i==PVDG_UI_ENGINEERING_DIAGNOSTICS;if((diag||s.write_ok)&&!s.busy)lv_obj_remove_state(s.sections[i],LV_STATE_DISABLED);else lv_obj_add_state(s.sections[i],LV_STATE_DISABLED);}}
void pvdg_ui_engineering_set_action_state(bool busy,const char*message){s.busy=busy;if(!s.root)return;if(message)pvdg_ui_label_set_if_changed(s.status,message);if(busy)lv_obj_add_state(s.login,LV_STATE_DISABLED);else lv_obj_remove_state(s.login,LV_STATE_DISABLED);}
