#include "pvdg_ui_source_setup.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pvdg_ui_theme.h"
typedef struct{lv_obj_t*root,*badge,*msg,*refresh,*save,*grid,*gen,*poll,*stale;pvdg_ui_source_config_t cfg;pvdg_ui_source_setup_callbacks_t cb;bool available,write,busy;}ui_t;static ui_t s;static lv_obj_t*field(lv_obj_t*p,const char*n){lv_obj_t*r=lv_obj_create(p);pvdg_ui_style_root(r);lv_obj_set_width(r,LV_PCT(100));lv_obj_set_height(r,44);lv_obj_set_layout(r,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(r,LV_FLEX_FLOW_ROW);lv_obj_t*l=pvdg_ui_make_muted(r,n);lv_obj_set_width(l,260);lv_obj_t*f=lv_textarea_create(r);lv_textarea_set_one_line(f,true);lv_obj_set_flex_grow(f,1);return f;}static void refresh(lv_event_t*e){(void)e;if(!s.busy&&s.cb.request_config)s.cb.request_config(s.cb.user);}static void save(lv_event_t*e){(void)e;if(!s.available||!s.write||s.busy||!s.cb.submit_config)return;pvdg_ui_source_config_t c=s.cfg;const char*p=lv_textarea_get_text(s.poll),*q=lv_textarea_get_text(s.stale);if(p&&p[0])c.evidence_poll_interval_ms=(uint32_t)strtoul(p,NULL,0);if(q&&q[0])c.evidence_stale_timeout_ms=(uint32_t)strtoul(q,NULL,0);char err[192];if(pvdg_ui_source_config_validate(&c,err,sizeof(err))!=PVDG_UI_SOURCE_CONFIG_OK){pvdg_ui_label_set_if_changed(s.msg,err);return;}s.cb.submit_config(&c,s.cb.user);}
lv_obj_t*pvdg_ui_source_setup_create(lv_obj_t*parent,const pvdg_ui_source_setup_callbacks_t*cb){memset(&s,0,sizeof(s));if(cb)s.cb=*cb;s.root=lv_obj_create(parent);pvdg_ui_style_root(s.root);lv_obj_set_size(s.root,LV_PCT(100),LV_PCT(100));lv_obj_set_layout(s.root,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(s.root,LV_FLEX_FLOW_COLUMN);pvdg_ui_make_title(s.root,"Source Setup");s.badge=pvdg_ui_make_badge(s.root,"Unavailable",lv_color_hex(PVDG_UI_COLOR_INACTIVE));s.msg=pvdg_ui_make_muted(s.root,"Load current source configuration.");s.grid=pvdg_ui_make_muted(s.root,"Grid evidence: --");s.gen=pvdg_ui_make_muted(s.root,"Generator evidence: --");s.poll=field(s.root,"Evidence poll interval (ms)");s.stale=field(s.root,"Evidence stale timeout (ms)");lv_obj_t*a=lv_obj_create(s.root);pvdg_ui_style_root(a);lv_obj_set_width(a,LV_PCT(100));lv_obj_set_height(a,50);lv_obj_set_layout(a,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(a,LV_FLEX_FLOW_ROW);s.refresh=lv_button_create(a);lv_obj_t*l=pvdg_ui_make_muted(s.refresh,"Refresh");lv_obj_center(l);lv_obj_add_event_cb(s.refresh,refresh,LV_EVENT_CLICKED,NULL);s.save=lv_button_create(a);l=pvdg_ui_make_muted(s.save,"Validate + Save");lv_obj_center(l);lv_obj_add_event_cb(s.save,save,LV_EVENT_CLICKED,NULL);if(s.cb.request_config)s.cb.request_config(s.cb.user);return s.root;}
void pvdg_ui_source_setup_set_config(const pvdg_ui_source_config_t*c){if(!s.root||!c)return;s.cfg=*c;s.available=true;char t[96];snprintf(t,sizeof(t),"Grid evidence: %s",pvdg_ui_source_grid_evidence_complete(c)?"configured":"not configured");pvdg_ui_label_set_if_changed(s.grid,t);unsigned gc=0;for(uint8_t i=0;i<3;i++)if(pvdg_ui_source_generator_evidence_complete(c,i))gc++;snprintf(t,sizeof(t),"Generator evidence channels: %u / 3",gc);pvdg_ui_label_set_if_changed(s.gen,t);snprintf(t,sizeof(t),"%lu",(unsigned long)c->evidence_poll_interval_ms);lv_textarea_set_text(s.poll,t);snprintf(t,sizeof(t),"%lu",(unsigned long)c->evidence_stale_timeout_ms);lv_textarea_set_text(s.stale,t);pvdg_ui_badge_set(s.badge,"Schema 4 loaded",lv_color_hex(PVDG_UI_COLOR_SUCCESS));}
void pvdg_ui_source_setup_apply_state(const pvdg_ui_source_setup_state_t*st){s.write=st&&st->write_allowed;s.busy=st&&st->busy;if(st&&st->message)pvdg_ui_label_set_if_changed(s.msg,st->message);if(!s.available||!s.write||s.busy)lv_obj_add_state(s.save,LV_STATE_DISABLED);else lv_obj_remove_state(s.save,LV_STATE_DISABLED);}
