#include "pvdg_ui_inverter_setup.h"
#include <stdio.h>
#include <string.h>
#include "pvdg_ui_theme.h"
typedef struct{lv_obj_t*root,*badge,*msg,*summary,*refresh,*save,*profiles;pvdg_ui_inverter_list_t list;pvdg_ui_inverter_profile_catalog_t catalog;pvdg_ui_inverter_assignment_map_t assignments;pvdg_ui_inverter_setup_callbacks_t cb;bool config_ok,profiles_ok,assign_ok,write,busy;}ui_t;static ui_t s;static lv_obj_t*button(lv_obj_t*p,const char*t,lv_event_cb_t cb){lv_obj_t*b=lv_button_create(p);lv_obj_t*l=pvdg_ui_make_muted(b,t);lv_obj_center(l);lv_obj_add_event_cb(b,cb,LV_EVENT_CLICKED,NULL);return b;}static void refresh(lv_event_t*e){(void)e;if(s.busy)return;if(s.cb.request_config)s.cb.request_config(s.cb.user);if(s.cb.request_profiles)s.cb.request_profiles(s.cb.user);if(s.cb.request_assignments)s.cb.request_assignments(s.cb.user);}static void save(lv_event_t*e){(void)e;if(!s.config_ok||!s.write||s.busy||!s.cb.submit_config)return;char err[192];if(pvdg_ui_inverter_list_validate(&s.list,err,sizeof(err))!=PVDG_UI_INVERTER_CONFIG_OK){pvdg_ui_label_set_if_changed(s.msg,err);return;}s.cb.submit_config(&s.list,s.cb.user);}
lv_obj_t*pvdg_ui_inverter_setup_create(lv_obj_t*parent,const pvdg_ui_inverter_setup_callbacks_t*cb){memset(&s,0,sizeof(s));if(cb)s.cb=*cb;s.root=lv_obj_create(parent);pvdg_ui_style_root(s.root);lv_obj_set_size(s.root,LV_PCT(100),LV_PCT(100));lv_obj_set_layout(s.root,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(s.root,LV_FLEX_FLOW_COLUMN);pvdg_ui_make_title(s.root,"Inverter Setup");s.badge=pvdg_ui_make_badge(s.root,"Unavailable",lv_color_hex(PVDG_UI_COLOR_INACTIVE));s.msg=pvdg_ui_make_muted(s.root,"Load inverter list and compiled profiles.");s.summary=pvdg_ui_make_muted(s.root,"Inverters: --");s.profiles=pvdg_ui_make_muted(s.root,"Profiles: --");lv_obj_t*a=lv_obj_create(s.root);pvdg_ui_style_root(a);lv_obj_set_width(a,LV_PCT(100));lv_obj_set_height(a,52);lv_obj_set_layout(a,LV_LAYOUT_FLEX);lv_obj_set_flex_flow(a,LV_FLEX_FLOW_ROW);s.refresh=button(a,"Refresh All",refresh);s.save=button(a,"Validate + Save Full List",save);refresh(NULL);return s.root;}
void pvdg_ui_inverter_setup_set_config(const pvdg_ui_inverter_list_t*list){if(!s.root||!list)return;s.list=*list;s.config_ok=true;char t[80];snprintf(t,sizeof(t),"Configured inverters: %u",(unsigned)list->count);pvdg_ui_label_set_if_changed(s.summary,t);char e[160];bool ok=pvdg_ui_inverter_list_validate(list,e,sizeof(e))==PVDG_UI_INVERTER_CONFIG_OK;pvdg_ui_badge_set(s.badge,ok?"Config valid":"Config invalid",lv_color_hex(ok?PVDG_UI_COLOR_SUCCESS:PVDG_UI_COLOR_DANGER));if(!ok)pvdg_ui_label_set_if_changed(s.msg,e);}
void pvdg_ui_inverter_setup_set_profiles(const pvdg_ui_inverter_profile_catalog_t*c){if(!s.root||!c)return;s.catalog=*c;s.profiles_ok=true;char t[96];snprintf(t,sizeof(t),"Compiled profiles: %u%s",(unsigned)c->count,c->truncated?" · truncated":"");pvdg_ui_label_set_if_changed(s.profiles,t);}void pvdg_ui_inverter_setup_set_assignments(const pvdg_ui_inverter_assignment_map_t*a){if(!a)return;s.assignments=*a;s.assign_ok=true;}
void pvdg_ui_inverter_setup_apply_state(const pvdg_ui_inverter_setup_state_t*st){s.write=st&&st->write_allowed;s.busy=st&&st->busy;if(st&&st->message)pvdg_ui_label_set_if_changed(s.msg,st->message);if(!s.config_ok||!s.write||s.busy)lv_obj_add_state(s.save,LV_STATE_DISABLED);else lv_obj_remove_state(s.save,LV_STATE_DISABLED);}
